name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_76424435-674f-4ea4-82e4-db7e263383df }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
